available_restaurants = [
    {
        "restaurantId": "1",
        "cuisine": "Chinese",
        "costBracket": "5",
        "rating": 3,
        "isRecommended": True,
        "onboardedTime": "2023-02-11",
    },
    {
        "restaurantId": "2",
        "cuisine": "NorthIndian",
        "costBracket": "5",
        "rating": 5,
        "isRecommended": False,
        "onboardedTime": "2023-02-11",
    },
    {
        "restaurantId": "3",
        "cuisine": "Chinese",
        "costBracket": "1",
        "rating": 1,
        "isRecommended": False,
        "onboardedTime": "2023-02-11",
    },
    {
        "restaurantId": "4",
        "cuisine": "Chinese",
        "costBracket": "2",
        "rating": 4,
        "isRecommended": True,
        "onboardedTime": "2023-02-15",
    },
    {
        "restaurantId": "5",
        "cuisine": "Chinese",
        "costBracket": "1",
        "rating": 3,
        "isRecommended": True,
        "onboardedTime": "2023-02-15",
    },
    {
        "restaurantId": "6",
        "cuisine": "Italian",
        "costBracket": "1",
        "rating": 3,
        "isRecommended": True,
        "onboardedTime": "2023-02-15",
    },
    {
        "restaurantId": "7",
        "cuisine": "Italian",
        "costBracket": "1",
        "rating": 4,
        "isRecommended": True,
        "onboardedTime": "2023-02-15",
    },
    {
        "restaurantId": "8",
        "cuisine": "Italian",
        "costBracket": "1",
        "rating": 3,
        "isRecommended": True,
        "onboardedTime": "2023-02-15",
    }
]
